// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Album struct {
	Albumid  int64  `json:"albumid"`
	Title    string `json:"title"`
	Artistid int64  `json:"artistid"`
}

type Artist struct {
	Artistid int64   `json:"artistid"`
	Name     *string `json:"name"`
}

type Customer struct {
	Customerid   int64   `json:"customerid"`
	Firstname    string  `json:"firstname"`
	Lastname     string  `json:"lastname"`
	Company      *string `json:"company"`
	Address      *string `json:"address"`
	City         *string `json:"city"`
	State        *string `json:"state"`
	Country      *string `json:"country"`
	Postalcode   *string `json:"postalcode"`
	Phone        *string `json:"phone"`
	Fax          *string `json:"fax"`
	Email        string  `json:"email"`
	Supportrepid *int64  `json:"supportrepid"`
}

type Employee struct {
	Employeeid int64      `json:"employeeid"`
	Lastname   string     `json:"lastname"`
	Firstname  string     `json:"firstname"`
	Title      *string    `json:"title"`
	Reportsto  *int64     `json:"reportsto"`
	Birthdate  *time.Time `json:"birthdate"`
	Hiredate   *time.Time `json:"hiredate"`
	Address    *string    `json:"address"`
	City       *string    `json:"city"`
	State      *string    `json:"state"`
	Country    *string    `json:"country"`
	Postalcode *string    `json:"postalcode"`
	Phone      *string    `json:"phone"`
	Fax        *string    `json:"fax"`
	Email      *string    `json:"email"`
}

type Genre struct {
	Genreid int64   `json:"genreid"`
	Name    *string `json:"name"`
}

type Invoice struct {
	Invoiceid         int64     `json:"invoiceid"`
	Customerid        int64     `json:"customerid"`
	Invoicedate       time.Time `json:"invoicedate"`
	Billingaddress    *string   `json:"billingaddress"`
	Billingcity       *string   `json:"billingcity"`
	Billingstate      *string   `json:"billingstate"`
	Billingcountry    *string   `json:"billingcountry"`
	Billingpostalcode *string   `json:"billingpostalcode"`
	Total             float32   `json:"total"`
}

type InvoiceLine struct {
	Invoicelineid int64   `json:"invoicelineid"`
	Invoiceid     int64   `json:"invoiceid"`
	Trackid       int64   `json:"trackid"`
	Unitprice     float32 `json:"unitprice"`
	Quantity      int64   `json:"quantity"`
}

type MediaType struct {
	Mediatypeid int64   `json:"mediatypeid"`
	Name        *string `json:"name"`
}

type Playlist struct {
	Playlistid int64   `json:"playlistid"`
	Name       *string `json:"name"`
}

type PlaylistTrack struct {
	Playlistid int64 `json:"playlistid"`
	Trackid    int64 `json:"trackid"`
}

type Track struct {
	Trackid      int64   `json:"trackid"`
	Name         string  `json:"name"`
	Albumid      *int64  `json:"albumid"`
	Mediatypeid  int64   `json:"mediatypeid"`
	Genreid      *int64  `json:"genreid"`
	Composer     *string `json:"composer"`
	Milliseconds int64   `json:"milliseconds"`
	Bytes        *int64  `json:"bytes"`
	Unitprice    float32 `json:"unitprice"`
}
